### ISSUE TITLE
Syntax highlighting problem in multiline string containing "CREATE"

### ISSUE THREAD

**Issue by JoarLeth** [atom/language-python#101]
Steps to reproduce:
1. Create a python file
2. Define a function, with a multinine string containing "CREATE" (within quotes)
```python
'''
"CREATE"
'''
print "Hi!"
```
"UPDATE" and "DELETE" give the same result, except those words get highlighted in a different color than the rest of the multiline string.

Expected result:
The code after the multiline string should be syntax highlighted as python code.

Actual result:
Everything after the multiline string is highlighted as if it were a string.

I'm on Atom 1.0.19 and I have disabled my Community Packages.

**Comment by JoarLeth** [comment]
Seems to coincide with this `(?=\\s*(SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER))`, which appears in four places in https://github.com/atom/language-python/blob/master/grammars/python.cson. "SELECT", "INSERT", "UPDATE", "DELETE", "CREATE", "REPLACE" and "ALTER" all give the same result.

**Comment by 50Wliu** [comment]
Ugh, this is due to greedy regex matching again, just like in #103.  Except this one will be harder to fix since the regex in question belongs to `language-sql` and not `language-python`.

**Comment by matheo** [comment]
I have the same issue
![bug pycolors](https://cloud.githubusercontent.com/assets/260185/10369389/98318260-6d9f-11e5-88d0-9f434177c367.png)

**Comment by soopanova** [comment]
Had the samething happen when i tried to put a long complex SQL query into """query""" made the rest of my code appear as a comment

**Comment by 50Wliu** [comment]
Closing in favor of #110 in order to consolidate the issue reports - feel free to subscribe there for updates.
