### ISSUE TITLE
Support for PEP 3107 and type hinting as in PEP 484

### ISSUE THREAD

**Issue by bziemons** [atom/language-python#111]
The syntax highlighting does not yet support function and function parameter annotations.
They were introduced in [PEP 3107](https://www.python.org/dev/peps/pep-3107/) and the syntax changes can be viewed there.

Except for annotating functions or their parameters there was not much of a use yet, but type hinting was introduced in Python 3.5 and uses PEP 3107 to give type information to developers and tools.
See [PEP 484](https://www.python.org/dev/peps/pep-0484/).

**Comment by 50Wliu** [comment]
Closing in favor of #68, please subscribe there for updates.
