### ISSUE TITLE
Atom doesn't recognize the '*.pyx' filetype

### ISSUE THREAD

**Issue by lzkelley** [atom/language-python#114]
`*.pyx` files are standard for use with [cython](http://docs.cython.org/index.html) -- which is a mix between python and c syntax.  For the most part cython code is just python code with c data types (and associated variable definitions, e.g.

    cdef int ii, max = 10
    for ii in xrange(max):
        print(ii)

Having the same syntax treatment for `.pyx` files would be a good start / fix.  Would it be possible to add a special grammar subset for `.pyx` files?

**Comment by teunzwart** [comment]
There is a package called [`language-cython`](https://atom.io/packages/language-cython) which does this.

**Comment by lzkelley** [comment]
Thanks @teunzwart, this can be closed I suppose.
