### ISSUE TITLE
In docstring, URL with underscore only partially recognized

### ISSUE THREAD

**Issue by nschneid** [atom/language-python#116]
<img width="1050" alt="url-bug" src="https://cloud.githubusercontent.com/assets/985263/11194181/906e7354-8ca2-11e5-92a0-a83a8901a315.png">

**Comment by diegoperini** [comment]
Correct author is this [Diego Perini](https://github.com/dperini)
:smiley:

**Comment by 50Wliu** [comment]
No longer repros, was probably fixed in language-hyperlink a while back.
![link-with-underscores](https://user-images.githubusercontent.com/2766036/35202353-2e644dce-fef0-11e7-897b-2c3dd8c18cf6.png)
