### ISSUE TITLE
Python highlighting problem

### ISSUE THREAD

**Issue by d33tah** [atom/language-python#117]
18.11.2015 12:44, James Dennes (GitHub Staff):
> Hi there,
> 
> We use open source TextMate-style language grammars for syntax highlighting, which are available here:
> 
> https://github.com/github/linguist/blob/master/grammars.yml
> 
> The fastest way to get this fixed would be to find the issue tracker for the specific grammar and open an issue or contribute a fix there.
> 
> Linguist pulls in grammar updates with each new release, which usually happens every couple of weeks. This should get fixed on GitHub.com shortly after that happens.
> 
>> Hello,
>>
>> I think that I might have found a bug in your syntax highlighting. Here it is:
>>
>> https://github.com/d33tah/pypgexplain/blob/c4693a14f7e411e8239195269474edcd0c6628dd/json_parse.py
>>
>> As you can see, the color-coding here isn't really readable - all text is marked as a string.
>>
>> Cheers,
>> d33tah

By the way, link to your guidelines for contributing is broken.

**Comment by 50Wliu** [comment]
Thanks for reporting.

**Comment by 50Wliu** [comment]
Looks like another SQL bug.

**Comment by d33tah** [comment]
Does that mean that it should be reported somewhere else?

**Comment by 50Wliu** [comment]
Possibly.  It could either be Python not recognizing the end of the string or SQL not recognizing one of the keywords.  I'd leave it here for now though.

**Comment by troytoman** [comment]
I have noticed a similar issue. If I have a word in a docstring that gets highlighted (in my case it is DELETE) it seems to throw off the recognition of the doc string and interprets the next triple quote as the beginning of a new docstring vs the end of the current one. 

if this text, for instance,
methods=['POST', 'DELETE'])
it will mess up the highlighting but if I change it to:
methods=['POST', 'delete']
everything looks correct

I see the same behavior in the sample referenced above with the word EXPLAIN

**Comment by 50Wliu** [comment]
Closing in favor of #110 in order to consolidate the issue reports - feel free to subscribe there for updates.
