### ISSUE TITLE
Triple quotes with SQL throws off highlighting. 

### ISSUE THREAD

**Issue by warrencs** [atom/language-python#118]
I'm using psycopg2 in python and I am writing SQL directly into the python script within triple quotes. Unfortunately, when I do this, it doesn't reset the text colors when the triple quotes end. I suspect that this has something to do with the AWS-redshift specific 'UNLOAD' syntax. Example attached. 

Atom version 1.2.1

<img width="785" alt="screen shot 2015-11-18 at 11 41 28 am" src="https://cloud.githubusercontent.com/assets/15333005/11252160/83617a6a-8de9-11e5-8919-9ec433487a51.png">

**Comment by nickcatal** [comment]
This appears to be an issue with any SQL-like syntax inside triple quotes

This presents the same problem (on github, which uses this bundle):
```python
    def query(self, query, **kwargs):
        """Return the result of a Salesforce SOQL query as a dict decoded from
        the Salesforce response JSON payload.
        Arguments:
        * query -- the SOQL query to send to Salesforce, e.g.
                   `SELECT Id FROM Lead WHERE Email = "waldo@somewhere.com"`
        """
        url = self.base_url + 'query/'
        params = {'q': query}
        # `requests` will correctly encode the query string passed as `params`
        result = self.request.get(url, headers=self.headers, params=params, **kwargs)
```

Screenshot:

<img width="562" alt="screenshot 2015-11-28 16 13 06" src="https://cloud.githubusercontent.com/assets/474748/11454238/f346a496-95ea-11e5-9186-e4edc47c916e.png">

**Comment by 3noch** [comment]
I'm seeing this as well.

**Comment by troytoman** [comment]
I am seeing the same problem which looks to be the issue I commented about in this thread:
https://github.com/atom/language-python/issues/117

**Comment by Yajo** [comment]
Same problem here. With an SQL:
![captura de pantalla de 2016-02-16 09-50-40](https://cloud.githubusercontent.com/assets/973709/13071329/f0ae5ba2-d492-11e5-8a23-9db5e907df43.png)

Without it:
![captura de pantalla de 2016-02-16 09-50-57](https://cloud.githubusercontent.com/assets/973709/13071330/f396a072-d492-11e5-86b5-10f339d4a7c1.png)

**Comment by 50Wliu** [comment]
Closing in favor of #110 in order to consolidate the issue reports - feel free to subscribe there for updates.
