### ISSUE TITLE
`yield from` highlighting

### ISSUE THREAD

**Issue by beregond** [atom/language-python#119]
![zrzut ekranu z 2015-11-19 11-48-07](https://cloud.githubusercontent.com/assets/956019/11268850/750fad0e-8eb3-11e5-8f92-4967ccdda538.png)

I think `yield from` should be colored green - it's not `import (...) from` directive.

**Comment by kbrose** [comment]
@50Wliu Can you clarify how this is feedback and not a bug?

**Comment by 50Wliu** [comment]
@kbrose Mostly because of the "I think" in the description.  I don't know Python, so I look at the wording of the issue to determine what it should be labeled as.  I can definitely see why this might be labeled as a bug though.

**Comment by kbrose** [comment]
@50Wliu Thanks!
