### ISSUE TITLE
Broken python syntax highlighting

### ISSUE THREAD

**Issue by foxx** [atom/language-python#124]
As you can see here, the syntax highlighting is broken (shows everything as a comment block).
https://github.com/bottlepy/bottle-sqlite/blob/master/bottle_sqlite.py

Also reported here (as instructed by Github staff);
https://github.com/github/linguist/issues/2793#issuecomment-168386556

**Comment by lee-dohm** [comment]
This is a duplicate of #118. Please subscribe there for updates.
