### ISSUE TITLE
Python formatting of numeric function parameters is inconsistent

### ISSUE THREAD

**Issue by mnquintana** [atom/language-python#127]
_From @skewty on January 7, 2016 15:56_

```
data = sock.recv(1024)
sock.recv(1024)
```

without the '=' the number is not colored

_Copied from original issue: atom/atom#10322_

**Comment by mnquintana** [comment]
_From @skewty on January 7, 2016 15:58_

This bug actually extends to more than numerics.

```
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
x = sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

Notice that the SOL_SOCKET and SO_REUSEADDR lose their color when the 1 gets it.

**Comment by 50Wliu** [comment]
No longer repros.
