### ISSUE TITLE
Support for Russian Cyrillic

### ISSUE THREAD

**Issue by KrassZen** [atom/language-python#128]
Support for Russian Cyrillic
Hello dear developers. Need support Cyrillic pothan interpreter.

**Comment by lee-dohm** [comment]
Atom has support for a number of encodings, some of which support Cyrillic, such as the various Unicode encodings. I'm not sure which versions of the Python language support Unicode for source code, but that would be up to the Python interpreter to handle, not Atom.

If you're running into an issue with Cyrillic characters in Atom, please share as much information as you can and file a new bug on the https;//github.com/atom/atom repository.

Thanks!
