### ISSUE TITLE
Symbols in python file no longer being detected

### ISSUE THREAD

**Issue by morganwahl** [atom/language-python#131]
When I press Ctrl-R in a python file, it says "No symbols found". Syntax highlighting works, and the bar at the bottom says "Python", so detection of the filetype works. I can't seem to find any logs with error messages. Not sure how to proceed

Using Atom 1.4.0 on Ubuntu 14.04.

**Comment by morganwahl** [comment]
Same thing with Atom 1.4.1.

**Comment by morganwahl** [comment]
Same thing with `--safe`

**Comment by morganwahl** [comment]
Don't see any error messages in the console.

**Comment by morganwahl** [comment]
(By "console" I mean the developer tools console.)

**Comment by morganwahl** [comment]
Uninstalled atom, deleted my ~/.atom dir, reinstalled, still have the same issue.

**Comment by amytruong** [comment]
Interestinggggg. I tried to reproduce but no luck on my end, however I'm on Atom 1.4.1 on Ubuntu 15.10. :confused: 
Would you mind sharing a simple script that you would expect to work to make sure I'm seeing what you're seeing?

One more thing, have you tried using the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms)? It will show you what key Atom saw you press and the command that was triggered because of it.

**Comment by morganwahl** [comment]
Here's a simple script:

```py
hello = 1

def dude():
    pass
```

The symbols "hello" and "dude" should be detected.

I tried the keybind resolver. It gives a green line (that I can't select to copy-paste here :-/):

```
symbols-view:toggle-file-symbols    .platform-linux atom-text-editor    /usr/share/atom/resources/app.asar/node_modules/symbols-view/keymaps/symbols-view.json
```

Investigating this path:

```sh
$ ls /usr/share/atom/resources/app.asar -lh
-rw-r--r-- 1 root root 73M Jan 25 14:25 /usr/share/atom/resources/app.asar
```

That file seems to be some kind of archive, but `file` doesn't know what it is. However, I see next to it another directory called app.asar.unpacked with this interesting subdir:

```sh
$ ls -R /usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/
/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/:
lib  node_modules  vendor

/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/lib:
ctags-config

/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/node_modules:
ctags

/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/node_modules/ctags:
build

/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/node_modules/ctags/build:
Release

/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/node_modules/ctags/build/Release:
ctags.node

/usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor:
ctags-darwin  ctags-linux  ctags-win32.exe
```

So no file that corresponds to what the Key Binding Resolver is saying. No clue if that matters.

I'll try uninstalling, deleting the /usr/share/atom dir, and reinstalling.

**Comment by morganwahl** [comment]
Nevermind, pointless lead. Clearly I don't understand what app.asar is.

Uninstalling atom completely removed `/usr/share/atom` on it's own. Looking at the .deb packges for 1.4.1 and some past versions, `keymaps` has never been in `app.asar.unpacked/node_modules/symbols-view/`.

**Comment by morganwahl** [comment]
Here's maybe a real clue:

```sh
$ /usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-linux
ctags-linux: Unknown option: --regex
```

**Comment by morganwahl** [comment]
Fudge! Problem was my `~/.ctags` file had an invalid line (with the nonexistant `--regex` arg). Sorry!

Is see `ctags` exits with a non-zero value in this case; is there someplace within atom I could see that as a clue?

**Comment by morganwahl** [comment]
Oh well, just closing. Only real bug here is the lack of clues in the atom interface.

**Comment by 50Wliu** [comment]
> Only real bug here is the lack of clues in the atom interface.

This probably deserves its own issue :wink:.

**Comment by morganwahl** [comment]
Done: https://github.com/atom/symbols-view/issues/145

**Comment by yuas-Crypter** [comment]
Recently, I installed Atom on my MacBook and tried to learn Python programming. 
When I finish typing code and hit CMD+R, it always says "no symbols found."
I did some research and some say I need to boot the application via terminal and I did, but same problem happens every time. 
Do you have any idea how to solve this problem?
Please help me out.
OS:OS:OSX 10.13.2（17C88）
Atom:1.23.3 x64
