### ISSUE TITLE
Documentation for grammar files

### ISSUE THREAD

**Issue by kbrose** [atom/language-python#135]
Where can we find documentation for the grammar definitions found in the files in https://github.com/atom/language-python/tree/master/grammars?

It looks like it might be the format found at https://manual.macromates.com/en/language_grammars but with extra quotes around everything, is that correct?

**Comment by 50Wliu** [comment]
Yes, exactly.  The tm format is XML; Atom's is CSON.  We're working towards more robust documentation though (cc @MaximSokolov for the relevant issues).

**Comment by kbrose** [comment]
@50Wliu Thanks, you should feel free to close the issue whenever you're ready.
