### ISSUE TITLE
Documentation for settings files

### ISSUE THREAD

**Issue by kbrose** [atom/language-python#137]
Related to #135, but concerning settings files, i.e. [`settings/language-python.cson`](https://github.com/atom/language-python/blob/master/settings/language-python.cson).

Where can I find documentation about what possible keys are, specifically in

```cson
'.source.python':
  'editor':
    # what can I put here?
```

**Comment by kbrose** [comment]
It looks like running `atom.workspace.getActiveTextEditor().config()` in the developer tools returns the following list:

![configs](https://cloud.githubusercontent.com/assets/4053170/14049263/1883527e-f282-11e5-82e7-8653affa243e.png)

Are there any other options?

**Comment by kbrose** [comment]
Further snooping looks like the file [`atom/src/language-mode.coffee`](https://github.com/atom/atom/blob/master/src/language-mode.coffee) is where these config settings are being used.

**Comment by lee-dohm** [comment]
If I'm understanding your question correctly, the list of language-specific configuration options can be found in the Flight Manual here:

http://flight-manual.atom.io/using-atom/sections/basic-customization/

**Comment by kbrose** [comment]
@lee-dohm thanks for the response. Unfortunately, that page does not seem to have a complete list of all available keys. For example, you can do a ctrl+f search for "increase" and there are no results, even though this package (and others) use the "increaseIndentPattern" key (see https://github.com/atom/language-python/blob/master/settings/language-python.cson#L8). Indeed, while that page claims to have a current list:

```
editor.tabLength
editor.softWrap
editor.softWrapAtPreferredLineLength
editor.preferredLineLength
editor.scrollPastEnd
editor.showInvisibles
editor.showIndentGuide
editor.nonWordCharacters
editor.invisibles
editor.autoIndent
editor.normalizeIndentOnPaste
```

it does not mention *any* of the settings used in this repo:

```cson
'.source.python':
  'editor':
    'autoIndentOnPaste': false
    'softTabs': true
    'tabLength': 4
    'foldEndPattern': '^\\s*"""\\s*$'
    'commentStart': '# '
    'increaseIndentPattern': '^\\s*(class|def|elif|else|except|finally|for|if|try|with|while)\\b.*:\\s*$'
    'decreaseIndentPattern': '^\\s*(elif|else|except|finally)\\b.*:'
```

Perhaps the answer is just that the documentation is out of date and/or incomplete and that's a separate issue to file somewhere else...

**Comment by lee-dohm** [comment]
Pretty much any documentation request you have should be filed on the https://github.com/atom/flight-manual.atom.io repository. (Or you can now just go to the relevant page in the Flight Manual and click the "Improve this Page" link in the upper right to submit a fix yourself :grinning:)
