### ISSUE TITLE
Raw strings broken

### ISSUE THREAD

**Issue by Winseven4lyf** [atom/language-python#150]
### Description

The Python Language's raw string functionality is broken
### Steps to Reproduce

``` Python
print(r"\")
```

**Expected behavior:** String stops there because of the `r`.

**Actual behavior:** Atom language thinks the string continues, regardless of the `r`.
### Versions

apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.1.windows.1
visual studio
windows 10 #

**Comment by tsivula** [comment]
Related problem: 
![temp](https://cloud.githubusercontent.com/assets/4025364/18632607/e1ec4866-7e80-11e6-91e5-eb3824dbd84e.jpg)

The mismatching braces breaks the syntax colouring in the future. However, this `r"Set (0,2]"` and this `"""Set (0,2]"""` work.

**Comment by 1st1** [comment]
> `print(r"\")`

This code isn't valid Python.

**Comment by 50Wliu** [comment]
To add onto what @1st1 said:
> r"\\" is not a valid string literal (even a raw string cannot end in an odd number of backslashes). Specifically, _a raw literal cannot end in a single backslash_ (since the backslash would escape the following quote character).

From https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals.

Closing as `wontfix`.
