### ISSUE TITLE
the.<TAB> snippet that changes this to self. should only be triggered if it is after whitespace

### ISSUE THREAD

**Issue by talkaminker** [atom/language-python#154]
Description

the.<TAB> snippet that changes this to self. should only be triggered if it is after whitespace or after ",([
Meaning,
writing:
blah.<TAB> will turn into blahself. which is undesired
instead the .<TAB> autocomplete should only be applied if it is preceded by whitespace or if it in the beginning of sentence
Versions

vanilla latest 1.10

**Comment by talkaminker** [comment]
Why isn't this a bug? nobody wants blah.<TAB> to expend to blahself.

**Comment by talkaminker** [comment]
exactly!
right now, blah. **will** expand to blahself.
this is the behavior that should be fixed

**Comment by j2bbayle** [comment]
This should definitely be a bug!
It can become really annoying, especially when writing documentation where correct sentences end with a dot `.`, turned into `self.` when pressing "Enter" for a new line.
