### ISSUE TITLE
"DELETE" in string messes up syntax highlighting

### ISSUE THREAD

**Issue by dtenenba** [atom/language-python#161]
The following code:

``` python
            if method in ['PUT', 'DELETE']:
                if method == 'DELETE':
                    raise NotImplementedError("DELETE REST API calls aren't currently supported")
                response = self.__putCall__(url, headers, data)
                response =  response.split()[-1] # discard upload status msg (from curl put?)

```

Looks like this in Atom 1.11.2 and python-syntax 0.45.0:

![image](https://cloud.githubusercontent.com/assets/2286826/19571381/d224bad6-96b2-11e6-9f16-a1f22f94e701.png)

Everything after line 147 is green. If I remove the word `DELETE` from that line things look ok:

![image](https://cloud.githubusercontent.com/assets/2286826/19571542/5ae88c6c-96b3-11e6-92ae-dd5f1fc2fc59.png)

**Comment by tsivula** [comment]
"UPDATE" does the same

**Comment by scttcper** [comment]
'SELECT' does the same for me. Looks like the sql highlighting is not ending.

**Comment by tsivula** [comment]
It seems this has already been covered in issue #143. Disabling `language-sql` seems to be a quick fix for this.

**Comment by dtenenba** [comment]
I guess I'll close this as it's a duplicate (also of #143 and [atom/atom#12146](https://github.com/atom/atom/issues/12146)).
