### ISSUE TITLE
Automcomplete snippet for `class` not showing up in list

### ISSUE THREAD

**Issue by rkpatel33** [atom/language-python#162]
Today, I opened a project and am not seeing the usual Python snippets from the `language-python` package. I am not sure what could have happened, it was working last night just fine.

See the image below, the `class` from the package is missing. `def` seems to work fine.

![image](https://cloud.githubusercontent.com/assets/3799489/19615362/0c6d2af6-97cc-11e6-94ce-cce64ae5e044.png)

**Comment by 50Wliu** [comment]
This seems to be working for me - if you're still unable to see the `class` snippet please let me know and I'll investigate further.
