### ISSUE TITLE
BUG: Hint syntax isn't highlighted correctly

### ISSUE THREAD

**Issue by Olian04** [atom/language-python#166]
When using hints for arguments, the color coding gets a bit mixed up. But when using hints for return types a good couple of statements after the `->` lose there highlighting entirely.
![](http://i.imgur.com/2pLu69v.png)

__Info:__
* language-python 0.45.0
* atom 1.11.2
* Ubuntu 16.04 (64-bit)

**Comment by 50Wliu** [comment]
This is a duplicate of #68 - feel free to subscribe there for updates.
