### ISSUE TITLE
Tokenize methods

### ISSUE THREAD

**Issue by mehalom** [atom/language-python#170]
![2016-11-19 16 09 22](https://cloud.githubusercontent.com/assets/21067774/20456500/2b160c3a-ae91-11e6-8711-72f1b87da927.png)
metods as .split() .open() and any similar constructions is't recognized.

**Comment by MilyMilo** [comment]
+1 This would be neat. How hard is this to implement? Java and JS packages already have this. I'd massively boost readability. 
![screenshot from 2017-06-10 09-07-37](https://user-images.githubusercontent.com/24303006/27000904-592fa2d2-4dbc-11e7-8bd3-c4ee9b54ae8a.png)
![screenshot from 2017-06-10 09-06-58](https://user-images.githubusercontent.com/24303006/27000903-592ee342-4dbc-11e7-978c-818645237901.png)

**Comment by 50Wliu** [comment]
> How hard is this to implement?

In theory, not too difficult if language-python is organized somewhat similarly.  However, this is one of the most poorly maintained language packages, and at least for the short term we're [planning](https://github.com/atom/atom/pull/13877) to switch to MagicPython.

I would gladly review a PR adding function/method highlighting.
