### ISSUE TITLE
syntax hillighting bug

### ISSUE THREAD

**Issue by bglgwyng** [atom/language-python#171]
```python
def a(fn):
    return b[0](fn())
    
a()(lambda x:x)
```
This code is meaningless and is just written to reproduce the bug. In my atom, `lambda` in the last line isn't hilighted.

I've checked atom contribution guide but I'm worried that this is the right place to report this issue.

**Comment by 50Wliu** [comment]
No longer repros.
![python-lambda](https://user-images.githubusercontent.com/2766036/35202467-e844ce9e-fef0-11e7-8712-e28879ae6d34.png)
