### ISSUE TITLE
Not detecting file with shebang as Python

### ISSUE THREAD

**Issue by OmgImAlexis** [atom/language-python#173]
I'm not sure if this is the correct repo for this issue but I was expecting since *NIX doesn't care about file extensions that files starting with the Python shebang would be detected as Python.

For example I have a file called "test" with this body and it isn't detected as anything but "plain text".

```
#! /usr/bin/env python

print "Hello World!"
```

Yet if I call the file "test.py" then it works fine.

**Comment by 50Wliu** [comment]
Remove the leading space and it'll work.

**Comment by ValarDragon** [comment]
I believe this was fixed in #181

**Comment by 50Wliu** [comment]
Thanks @ValarDragon!
