### ISSUE TITLE
[ in character class breaks syntax highlighting

### ISSUE THREAD

**Issue by SanketDG** [atom/language-python#174]
### Description

Python syntax highlighting is broken.

### Steps to Reproduce

Just open this file in the atom editor, Line 52 is where the chaos begins
https://github.com/coala/coala-bears/blob/f72c246f9967d498660668512cd8f99eae7589fe/bears/general/InvalidLinkBear.py

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```
$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 3.5.2
git 2.9.3
```

I am on Fedora 25.

**Comment by bgschiller** [comment]
I'm experiencing a similar issue, but with SQL string literals instead of regex. Here's what it looks like:

![](http://162.209.109.174/2016-12-13_19-49-213JIGAH.png)

Here's the code to reproduce:

```

def function_name(arg1, arg2, **kwargs):

    x = sum(xrange(12))
    # code highlighting works up here

    """
        SELECT * FROM pg_indexes;
        {# Jinja2 comment with a ' goes right here #}
    """))

    for line in the_rest_of_the_file:
        looks_like(string_literal)
        but(its_code())


def other_function(green):
    pass
```

```
$ atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.2.1
```

I'm on OS X 10.11.4

**Comment by 50Wliu** [comment]
@bgschiller Your issue is #110.

**Comment by dborstelmann** [comment]
@SanketDG See the comment on #110 I made.

**Comment by SanketDG** [comment]
This issue is still there, the original file was from master and was updated a lot. I have pointed to the specific committed file before I opened the issue
