### ISSUE TITLE
tabLength doesn't change how tabs are displayed

### ISSUE THREAD

**Issue by ledm** [atom/language-python#175]
For better of worse,I have a lot of python code with the assumption that the tab length is 8.

When I change tabLength to 8 (both in editor settings and language settings), it still displays python with a tab length of 4. I've only found this issue with python, other file types are displayed correctly.

**Comment by chaen** [comment]
I found out that if the global tab length is the same as the python tab length, then the 4 spaces (default pep-8) are used. 
So if you have different settings, it works as expected

**Comment by Jma353** [comment]
+1

**Comment by zyf0330** [comment]
TabLength of my atom editor default settings is 2, and settings in language-python shows 2 too. But actually it is 4 when I code in py files. I must add `tabLength: 2` into `".python.source":\n  editor:` config.cson manually to specify it.

**Comment by JellyWX** [comment]
I've opened this issue and it has been closed as apparently it needs to be brought up somewhere else. Don't expect this issue to stay open long

**Comment by miguelroboso** [comment]
I have the same issue. It doesn't matter how much I put in "Tab Length" (in settings, or "tabLength" in config.cson), in python I always have tabs of 4 spaces (soft tab).

**Comment by stevenkkim** [comment]
Thanks @zyf0330  – I had the exact same problem with 4-spaced tabs even though I specified 2 spaces in setting, and your config.cson changes worked perfectly for me. Thanks!!

**Comment by MatthewSteen** [comment]
more specifically than [zyf0330 commented on Jan 9](https://github.com/atom/language-python/issues/175#issuecomment-271226931) adding the following to the `config.cson` file works:

```
".python.source":
  editor:
    tabLength:2
```

**Comment by 50Wliu** [comment]
I believe that this was a Settings View bug that has been fixed on recent versions of Atom.
