### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by JLCCI** [atom/language-python#179]
Sorry if this is something that was described elsewhere but I cannot find an answer. 

I am writing Python 3 scripts and just moved to Fedora. Unfortunately the default Python version on Fedora is 2. This makes the linter treat all Python scripts as ver. 2 and highlights wrong type of errors.

Is there any way of making Atom (and linter) switch to Python 3? I do not need Python 2 at all.  There is a pull requests but it has not moved for a while.

Many thanks!

**Comment by 50Wliu** [comment]
We are in the progress of moving to the MagicPython highlighter which supports Python 3 - just waiting for the people involved to send a PR.  As for linting, you would have to ask on the appropriate linter repos or the `#linter` channel on Slack.
