### ISSUE TITLE
Indent with tab length 2 doesn't work

### ISSUE THREAD

**Issue by willdzeng** [atom/language-python#187]
### Description

Auto indent with tab length 2 doesn't work

**Expected behavior:** a tab should be 2
![image](https://cloud.githubusercontent.com/assets/12994633/23531621/2dae149e-ff5c-11e6-95b9-7b911b3a451e.png)
![image](https://cloud.githubusercontent.com/assets/12994633/23531680/68e5a1a8-ff5c-11e6-8cf0-b502c83d3e74.png)

**Actual behavior:**  always give 4 spaces
![image](https://cloud.githubusercontent.com/assets/12994633/23531641/42eb1bfe-ff5c-11e6-96e6-49c666e591a4.png)

### Versions
System : Ubuntu 16.06
Atom    : 1.14.2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment]
Please create a new issue on atom/settings-view for this.

**Comment by alexeypetrushin** [comment]
Same issue
