### ISSUE TITLE
Broken GitHub highlighting for Python C extension traceback

### ISSUE THREAD

**Issue by KeyWeeUsr** [atom/language-python#188]
I'm not sure if this is the right repo, but I got a hint from GitHub Staff that it's one of [these](https://github.com/github/linguist/tree/master/vendor) repos that is responsible for this bug. Please point me to the right one if I got it wrong. This one is labeled as `traceback` though:

> Python traceback: atom/language-python

The problem is basically a Windows path in traceback because it contains backslash (`\`). The lexer tries to do something(variable highlight? class?) but fails.

Reproduce with:

> &grave;&grave;&grave;python
&lt;code&gt;
&grave;&grave;&grave;

```python
C:\Users\blob
   ↑

C:\\Users\\blob
   ↑

'C:\Users\blob'
string is ok

File "kivy\_clock.pyx", line 75, in kivy._clock.ClockEvent.__call__ (kivy\_clock.c:2223)
     self.clock._lock_release()                                           ↑
full line
```

**Comment by vpetrovykh** [comment]
Please note that if you use the correct language association, the highlighting should work fine:

> \`\`\`python-traceback 
> \<code>
> \`\`\`

```python-traceback
C:\Users\blob
   ↑

C:\\Users\\blob
   ↑

'C:\Users\blob'
string is ok

File "kivy\_clock.pyx", line 75, in kivy._clock.ClockEvent.__call__ (kivy\_clock.c:2223)
     self.clock._lock_release()                                           ↑
full line
```

So the question is: why is traceback highlighted with python highlighter as opposed to python-traceback one? Can you provide more context, such as the editor you're using?

**Comment by KeyWeeUsr** [comment]
Well, it's highlighted because I used `python` instead of `python-traceback` as the highlighting language. There's no "editor", I just used GitHub forms in pull requests, issues, wiki, etc.

If there's a separate thing I can choose for traceback (`python-traceback`), then it's only my fault for using `python` explicitly on lines it should be used for. Thanks for the explanation.

**Comment by 50Wliu** [comment]
Feel free to open an issue detailing what enhancements you'd like to see for the traceback grammar.
