### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by hienchu** [atom/language-python#193]
You have the core package "language-python" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:32)
```

**Comment by hienchu** [comment]
the "deprecation" indicator is always there while it says "All of your installed packages are up to date!" when checking for updates.

**Comment by Ben3eeE** [comment]
You have the core package "language-python" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
