### ISSUE TITLE
Tabs In Python Syntax

### ISSUE THREAD

**Issue by AngelDHurtado** [atom/language-python#199]
### Description

In the language-python 0.45.2 package, set Tab Length to the given value in the editor configuration but not apply to the syntax in python

### Steps to Reproduce

1. Open a file python

**Expected behavior:** In the language-python 0.45.2 package set Tab Length to the value determined in the editor configuration and apply to the syntax in python

**Actual behavior:** The language-python 0.45.2 package sets Tab Length to the value determined in the editor configuration and applies to the syntax

**Reproduces how often:** Always

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by soundconjurer** [comment]
I second this.

**Comment by 50Wliu** [comment]
This sounds like a duplicate of atom/settings-view#939.
