### ISSUE TITLE
Incorrect highlighting of raw bytes with non-decimal chars in strings

### ISSUE THREAD

**Issue by ValarDragon** [atom/language-python#200]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In strings, normally '\xXX' makes the char at that position chr(int(XX,16)), it converts the hex value XX into that raw byte. However if one of the chars in X is non-decimal (so a-f) it doesn't get recognized. 

### Steps to Reproduce

Create the string "\x44\xff\x32RandomString\xa4\x4a\x44" in atom, and observe that the bytes with non decimal chars don't get highlighted. 

**Expected behavior:** 

All escaped hex bytes inside of strings to be highlighted.

**Actual behavior:** [What actually happens]

![image](https://i.imgur.com/dBNQcNW.png)

**Reproduces how often:** 100% of the time for me

### Versions

I am on Linux Mint 17.3

atom 1.6.2
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

**Comment by 50Wliu** [comment]
Fixed by #215.
