### ISSUE TITLE
Auto-indentation handling "else:" de-indent incorrectly.

### ISSUE THREAD

**Issue by aseyffert** [atom/language-python#210]
When constructing an if statement which contains indented blocks (like the one below) the expected behaviour of the auto-indentation is to take the ```else:``` to the same level as the associated ```if ...:```, not only one indent left. If the ```if ...:``` block doesn't end with and indented block the ```else:``` is indented correctly.

This is wrong:
```
if fooBool:
    for i in range(fooMax):
        barF(i)
    else:
        print 'Whoops'
```

This is right:
```
if fooBool:
    for i in range(fooMax):
        barF(i)
else:
    print 'There we go...'
```

**Comment by csvoss** [comment]
My guess is that this happens because of Python's `for-else` loops. It's trying to align the `else` with the `for`.

https://docs.python.org/2/reference/compound_stmts.html#the-for-statement

**Comment by aseyffert** [comment]
I'll be honest, I didn't even know ```for-else``` loops existed. I guess there is no issue then, except my ignorance... :sweat_smile:

Thanks @csvoss!
