### ISSUE TITLE
Chained nested function calls confuse highlighting

### ISSUE THREAD

**Issue by Beefster09** [atom/language-python#238]
In this example, b will be highlighted as if it were a keyword argument:

    ()(a())
    b = c

Anything in the form `(.*)\s*(X(.*))` or `[.*]\s*(X(.*))` breaks highlighting.

**Comment by 50Wliu** [comment]
Thanks for the report, @Beefster09!  I believe that I've already fixed this and that highlighting should appear correct in upcoming Atom versions.
