### ISSUE TITLE
Highlight of placeholders in strings

### ISSUE THREAD

**Issue by Talon24** [atom/language-python#239]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When Using placeholders in Strings, usually the text inside the braces will be colored differently, but when I use the signs "<", "^", ">" inside the placeholder, it will not mark it as placeholder anymore.

### Steps to Reproduce

```
my_str = "It is I, String"
res_str = "Hello {:20}!".format(my_str)
res_str = "Hello {:^20}!".format(my_str)
print(res_str)
```

![2018-03-12 21_00_21-python py c__users_talon_documents_code atom](https://user-images.githubusercontent.com/13787063/37315612-d135dc70-265a-11e8-872e-295b0318e4cd.png)
![2018-03-13 01_05_37-python py c__users_talon_documents_code atom](https://user-images.githubusercontent.com/13787063/37315613-d151bb02-265a-11e8-96e5-e230362bf082.png)

**Expected behavior:** 

The text inside the placeholder will be colored when one of the symbols above are found inside.

**Actual behavior:**

The placeholder will not be colored.

**Reproduces how often:**

Everyime when <^> are used in placeholder.

### Versions

`atom --version`
Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

`apm --version` 
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.1
python 3.6.3
git

OS: Windows 10 Pro 64bit
Version	10.0.16299 Build 16299

**Comment by 50Wliu** [comment]
I recently fixed this and I believe it'll be available starting in Atom 1.25.0.
