### ISSUE TITLE
Python syntax highlighting: Import line is red

### ISSUE THREAD

**Issue by silentsokolov** [atom/language-python#241]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Import line uncolored in one case, and red in the next.

### Steps to Reproduce

1. Open any python file

**Expected behavior:**
Import line uncolored

**Actual behavior:**
Import line uncolored in one case, and red in the next.

**Reproduces how often:**
All time

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

I do not use `Tree-sitter Parsers`

![1521530272849](https://user-images.githubusercontent.com/398939/37640724-fa12796e-2c27-11e8-8e1c-af06bb591d3b.jpg)

**Comment by cscanlin** [comment]
Seeing a similar issue, it appears to be related to `.` characters applying styles that they should not be.

<img width="407" alt="screen shot 2018-03-20 at 9 17 28 am" src="https://user-images.githubusercontent.com/2954573/37667611-a2132e6e-2c1f-11e8-863f-3ee8dd72f7e3.png">

**Comment by silentsokolov** [comment]
I rollback to Atom 1.24.2, that's how it [looked before](https://user-images.githubusercontent.com/398939/37669048-f0ab47ee-2c76-11e8-975b-a7471a41d4d6.jpg) the update.

**Comment by jarekwg** [comment]
Yep.
As of atom 1.25.0, my imports (amongst other broken things) are highlighting differently depending on whether they have a . in them. Should always just be white there..
![image](https://user-images.githubusercontent.com/5036488/37805717-185df9e2-2e90-11e8-90f7-2704bce26235.png)

Definitely `.` related.
