### ISSUE TITLE
Folding methods with multiline arguments doesn't fold the entire method

### ISSUE THREAD

**Issue by jrial** [atom/language-python#242]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When folding a function or method that has too many arguments to fit on one line, the fold mark before the method only folds the arguments and not the entire method.

### Steps to Reproduce

1. Fold a function or method that has its arguments over multiple lines

**Expected behavior:** I expect the entire method to fold

**Actual behavior:** The arguments on the next line(s) are folded.

**Reproduces how often:** Always

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.14
git 2.7.4
OS: Linux Mint 18.3
Kernel: 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Demo animation:

![output](https://user-images.githubusercontent.com/570247/37836724-7bca823e-2eb3-11e8-8ee0-1cecccff2e61.gif)

**Comment by jrial** [comment]
Nevermind, apparently tree-sitter is responsible for this, and it's considered a feature, if I am to believe the tree-sitter section on https://blog.atom.io/2018/03/15/atom-1-25.html

Closing due to issue raised in wrong repo.

**Comment by halorium** [comment]
I was experiencing this issue. I made sure I was using an up-to-date version of Atom and then in core settings I disabled tree-sitter. The python function now folds the entire function. Maybe this will help others searching for a solution to this issue. :)

**Comment by rhausman** [comment]
I reproduced this issue without tree-sitter installed (I have never had it installed). I think folding the entire method is a really important feature. Is there any solution other than turning off tree-sitter?

**Comment by MetRonnie** [comment]
A workaround is to move the cursor to the last line of args (the line that has the `):`) and do <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>[</kbd>, or `editor:fold-current-row` in the command palette

**Comment by BastelBaus** [comment]
Still for me, 1.16.0, never tree-sitter installed. Any chance to get fixed ?
