### ISSUE TITLE
`lambda:` does not highlight `lambda` as a keyword

### ISSUE THREAD

**Issue by Beefster09** [atom/language-python#246]
### Description

If `lambda` is immediately followed by a colon, it will not be highlighted. If a space is inserted, it will again be highlighted as a keyword.

This is a problem if you sometimes create no-arg functions (`lambda: None` is useful quite often)

### Versions
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
language-python: 0.49.2

**Comment by HojinCho** [comment]
I probably have a relevant issue.
Variable names ending with `lambda`, such as `Blambda` is highlighted, but only the `lambda` part. 
(See attached image)

![image](https://user-images.githubusercontent.com/7287650/38017189-41a89a12-32ac-11e8-98a2-6916350877db.png)

This issue just appeared today, along with #245 and #241 .

Tested on
Atom    : 1.25.0
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
language-python : 0.49.2

**Comment by falcondai** [comment]
Yes, the lambda matching seems wrong: it matches variable name ending in `lambda` and expects a lambda function body to follow.

![screen shot 2018-04-13 at 12 20 50](https://user-images.githubusercontent.com/997426/38964393-3ba68c64-433c-11e8-92c8-36b5cac41504.png)

Atom: 1.26.0
language-python: 0.49.4
