### ISSUE TITLE
Feature request: allow stringEOL style ( ##this is a stringEOL )

### ISSUE THREAD

**Issue by WiliTest** [atom/language-python#250]
It would be great to be able to use the stringeol style:

#this is a code block header
##this is a comment (stringEOL)

This [stack answer](https://stackoverflow.com/a/7221958/1486850) talk about it.

**Comment by ambv** [comment]
Never heard of "STRINGEOL". What is it? The StackOverflow post doesn't answer this. It lists some obscure feature (or bug?) of Notepad++.

Doxygen is used very rarely in the Python community so I don't see value in styling it differently.

**Comment by WiliTest** [comment]
Thanks for your reply ! Stringeol would be us simply allow to have 2 types of comments style. So you could, for instance, use some font style for the `#normal comment` and some other font style for the `##comments` Look at this print screen :
![image](https://user-images.githubusercontent.com/24194840/38813685-f1b7f5aa-418f-11e8-8d3a-2f7fcc2b8094.png)

**Comment by Arcanemagus** [comment]
Everything I'm seeing shows this as a custom "feature" (bug in the parser combining a feature from another language) for Notepad++.

What official Python documentation can you provide justifying this functionality?

----

Note: "eol" almost always means "End of Line" and talks about the characters used to denote the end of a line in a file (eg. `CRLF`, or `LF` typically), "STRINGEOL" doesn't make much sense.

**Comment by WiliTest** [comment]
I'm surprised I did not find it in the official document, I just find it very handy. So I'll see if I can customize it myself, sorry to have wasted your time, and thanks a lot for your awesome work!

**Comment by 50Wliu** [comment]
Yes, I would consider creating a custom grammar package for this that hooks into (injects) or includes language-python.
