### ISSUE TITLE
Having 'lambda' at the end of the variable name breaks highlighting

### ISSUE THREAD

**Issue by jabozzo** [atom/language-python#268]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Having the string 'lambda' at the end of a variable to be assigned to a lambda expression breaks the highlighting for the lambda expression.

### Steps to Reproduce

1. Open a file
2. Set grammar to python
3. Write: f_lambda = lambda x: None

**Expected behavior:**
The variable name gets colored normally. The lambda keyword turns purple. And the parameters of the lambda colored orange.

**Actual behavior:**
The lambda string on the variable name gets coloured purple. The lambda keyword and the lambda parameters gets colored orange.

**Reproduces how often:**
Always

### Versions

Atom       : 1.28.2
Electron  : 2.0.5
Chrome  : 61.0.3163.100
Node      : 8.9.3
Ubuntu   : 18.04

### Additional Information
![image](https://user-images.githubusercontent.com/9649979/43231130-0d4d752c-9039-11e8-8f43-e655e242f58b.png)

**Comment by jabozzo** [comment]
You're right. In dev mode there is no bug. I don't know what's the difference between normal, safe and dev mode. But only in the latter the bug is not existent.

**Comment by brennenberkley** [comment]
The differences is that dev mode uses newer versions of the packages that haven't been released yet in a regular atom version, so this has already been fixed but the current version of atom doesn't contain the fix yet.
