### ISSUE TITLE
Do not automatically trim end of line white space

### ISSUE THREAD

**Issue by gabriel-r** [atom/language-python#27]
When opening a file, all white space at the end of each line is trimmed. 
This is quite annoying when diffing changes. 

![5psq4r_views_py__views_py_-_sourcegear_diffmerge](https://cloud.githubusercontent.com/assets/51084/3025177/508f559e-e002-11e3-9244-35df93ca3b0c.jpg)

**Comment by jacksonbicalho** [comment]
Disabled ignore whitespace only lines in PackagesWhitespace.

**Comment by ziru** [comment]
I disabled the "Remove Trailing Whitespace" option from the Whitespace package.  I did notice a menu item for this action on demand.  Just curious whether it is possible to add a keybinding for doing this?

**Comment by izuzak** [comment]
> I disabled the "Remove Trailing Whitespace" option from the Whitespace package. I did notice a menu item for this action on demand. Just curious whether it is possible to add a keybinding for doing this?

@ziru Yeah, that should be possible. For example, add this to your keymap.cson:

```
'atom-text-editor':
  'ctrl-alt-y': 'whitespace:remove-trailing-whitespace'
```

Also check out these docs:

https://atom.io/docs/latest/using-atom-basic-customization#configuring-with-cson
https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
https://atom.io/docs/latest/behind-atom-keymaps-in-depth
