### ISSUE TITLE
Python not highlighted with tree-sitter

### ISSUE THREAD

**Issue by chbk** [atom/language-python#283]
### Description

Python code isn't being highlighted when tree-sitter is enabled. The scope seems to be there:

![](https://user-images.githubusercontent.com/7478535/47965280-5d734200-e045-11e8-9325-3800105e5c8a.png)

But the html doesn't have an enclosing span with a `syntax--source syntax--python` class:

![](https://user-images.githubusercontent.com/7478535/47965294-7e3b9780-e045-11e8-914a-fd9b9bb463c1.png)

*Edit by @rsese to add code snippet to reproduce via https://github.com/atom/language-python/issues/283#issuecomment-437622246*

> this is actually due to a problem with f-strings. I wrote an example that will make the tree-sitter parser bug:

```python
a = [7]
b = a[0]
print(f'{b:03d} {b:03d} {b:03d} {b:03d}')
print(f'{a[0]:03d}')
```

In devtools for the first line:

![devtools](https://github-slack.s3.amazonaws.com/monosnap/test.py__worksteveward_2018-11-12_14-56-55.png)

### Versions

Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
language-python: 0.51.8

### Additional Information

Similar to language-go issue [159](https://github.com/atom/language-go/issues/159)

**Comment by chbk** [comment]
Perhaps this is due to `tree-sitter-python.cson` having a `module` scope instead of `source_file`?

```cson
scopes:
  'module': 'source.python'
```

**Comment by Ben3eeE** [comment]
I am unable to reproduce this on latest master:

![image](https://user-images.githubusercontent.com/1058982/47968561-16e50e00-e06c-11e8-9246-47db336f7d53.png)

**Comment by rsese** [comment]
Hmm, I couldn't reproduce either on macOS 10.12.6 with 1.34.0-nightly10 or with 1.32.1.

@chbk - does this happen for you in safe mode and with any Python file?

**Comment by rsese** [comment]
Thanks @chbk, I can reproduce with that code snippet :+1:, issue body is updated with these details.

![devtools](https://github-slack.s3.amazonaws.com/monosnap/test.py__worksteveward_2018-11-12_14-56-55.png)

**Comment by Ben3eeE** [comment]
Seems like a bug with parsing f-strings in tree-sitter-python /cc: @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Thanks for the minimal example @chbk; that made it really easy to fix the problem. We'll probably publish a new Atom version with the fix in the coming week.

**Comment by hermidalc** [comment]
Hi - am I missing something or is this fix still not available?  I have the latest atom with everything updated and when I turn on tree sitter parsers python highlighting looks wrong.
