### ISSUE TITLE
env header autocomplete does not replace beginning of line

### ISSUE THREAD

**Issue by wesinator** [atom/language-python#293]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The python env bang header autocomplete appends to the already typed text instead of replacing the beginning of the line, making it basically useless.

### Steps to Reproduce

1. File language set to Python
2. Start typing `#!/usr/bin/env`
3. select suggested `env`

![image](https://user-images.githubusercontent.com/5124946/53668902-49320100-3c43-11e9-856f-26a4040bf47f.png)

**Expected behavior:** env autosuggest replaces from beginning of line

**Actual behavior:** autosuggest appends full string on to `#!/usr/bin/`

![image](https://user-images.githubusercontent.com/5124946/53668989-97470480-3c43-11e9-9ca8-fbdff5280513.png)

**Reproduces how often:** always

### Versions

macOS
```
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by Aerijo** [comment]
While possibly unexpected behaviour, the intended use is without the previous `#!/usr/bin/`; simply expanding `env` will give you what you want.

**Comment by wesinator** [comment]
@Aerijo it isn't even autosuggested until `#!/usr/bin/e`

**Comment by Aerijo** [comment]
That's odd. I see it fine starting with a blank line.

**Comment by rsese** [comment]
> it isn't even autosuggested until #!/usr/bin/e

...

> That's odd. I see it fine starting with a blank line.

Same for me with 1.34.0 on macOS 10.12.6 - this is in safe mode where you don't see the suggestion by typing just `env` @wesinator?

**Comment by wesinator** [comment]
Yea, I misunderstood the alias per https://github.com/atom/language-python/issues/294#issuecomment-468970212

Sorry,
