### ISSUE TITLE
env is not autosuggested until "#!/usr/bin/env" is nearly typed out

### ISSUE THREAD

**Issue by wesinator** [atom/language-python#294]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

https://github.com/atom/language-python/issues/293#issuecomment-468856088
env header is not autosuggested until the string is nearly typed out

### Steps to Reproduce

Reproduced on macOS and Windows
1. New Python or existing python file
2. First line, start to enter `#!/usr/bin/env`

**Expected behavior:** Based on https://github.com/atom/language-python/issues/293#issuecomment-468846479 , sounds like it is expected to autosuggest env early

**Actual behavior:** env autosuggest does not appear until `#!/usr/bin/e` is typed

![image](https://user-images.githubusercontent.com/5124946/53682648-cd2ccd00-3cc5-11e9-9e28-c1c60bc2f822.png)

![image](https://user-images.githubusercontent.com/5124946/53682669-ec2b5f00-3cc5-11e9-92a2-eb3076c1101a.png)

**Reproduces how often:** always

### Versions

language-python 0.51.8
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by Aerijo** [comment]
> First line, start to enter #!/usr/bin/env

What happens if you start to enter `env` directly? That is the prefix for the snippet.

**Comment by wesinator** [comment]
Doh, yes typing it at the beginning works.

Is this documented anywhere ?

Thanks,
