### ISSUE TITLE
Numbers do not have numeric scope/class with tree-sitters

### ISSUE THREAD

**Issue by binaryfunt** [atom/language-python#295]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Numbers have scope `constant.language` instead of `constant.numeric` as in other languages e.g. JavaScript.

### Steps to Reproduce

1. In core settings make sure "use tree-sitters" is ticked
1. Open a Python file and type e.g. `a = 25`
1. On `25` open the command palette, type "log cursor scope" and hit enter

### Versions

Atom: 1.34.0
Electron: 2.0.16
Windows: 10 v1803

**Comment by Ben3eeE** [comment]
https://github.com/atom/language-python/pull/288 fixes this.
