### ISSUE TITLE
Atom crashing when changing if statements  

### ISSUE THREAD

**Issue by djw1809** [atom/language-python#302]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashing in safe mode when changing any if statement in a particular .py file.

### Steps to Reproduce

1. Open file
2. change any if statement (for example change to an elif)

**Expected behavior:** Editor continues as normal and highlights statements correctly

**Actual behavior:** Editor crashes

**Reproduces how often:** 100%

### Versions

1.36

### Additional Information

Only seems to happen with a particular python file.

**Comment by 50Wliu** [comment]
@djw1809 can you please try Atom 1.37 beta? We fixed a crash related to editing Python code in that version.

**Comment by djw1809** [comment]
This seemed to solve the issue.  Thanks - I was having a difficult time reproducing it in a different file.

**Comment by 50Wliu** [comment]
Great, thank you!
