### ISSUE TITLE
'in' is not highlighted if used after a for statement

### ISSUE THREAD

**Issue by rohit49plus2** [atom/language-python#304]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

'in' and the subsequent indented code block is not highlighted when used after a for statement.

### Steps to Reproduce

1. Any statement like "for item in list:" will not highlight the 'in' keyword.

**Expected behavior:** Syntax highlighting for the 'in' keyword.

**Actual behavior:** No highlighting
![bug-python-highlighting-in](https://user-images.githubusercontent.com/31304798/58442040-68093c00-813b-11e9-9295-57c5d8ef9e69.png)

**Reproduces how often:** 100% of the time

### Versions
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report!   I'm unable to reproduce on macOS 10.12.6 with 1.37.0 using your example (not sure if line 2 is cut off or not, sharing the entire example for copy/pasting is helpful):

```python
for item in pi:
    sanctioncondition = item[0] in sanction_codes and item[1] in doi
    if sanctioncondition:
        return True
return False
```

Screenshot:

![python-in](https://user-images.githubusercontent.com/734194/58522365-9a3f8b80-8185-11e9-957f-e17ae125137f.png)

Can you reproduce with this example as well?

```python
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
```
