### ISSUE TITLE
Info boxes that shown from left side, don't hide

### ISSUE THREAD

**Issue by canturkm** [atom/language-python#308]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
I couldn't reproduce the bug using safe mode. Because bug is in the package. 

    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    X Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    X Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>

    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>
It is not a feature request.

### Description
When I go over the info/warning boxes on the left side, message boxes pop up. However, those boxes don't hide anyway. I think this gif explains very well, what the bug is. 

![atom-language-python-bug](https://user-images.githubusercontent.com/10234479/61996828-cb630c00-b0a1-11e9-8367-4d492d21d0a7.gif)

My installed packages are:
![atom-language-python-bug2](https://user-images.githubusercontent.com/10234479/61996847-ec2b6180-b0a1-11e9-9145-01b0f54d7292.gif)

I have 4 python packages installed to my Atom IDE:  autocomplete-python, ide-python, python-indent and python-tools. I disabled 4 of them and tried to reproduce the bug. Bug is reproduced. 

When I disabled, language-python package from "Core Packages" the bug didn't reproduce. So, I decided to report this bug to related core atom package. 

### Steps to Reproduce

1. Open a python file.

**Expected behavior:**

Hiding the info boxes after a while.

**Actual behavior:**

Shown info box stays there forever.

**Reproduces how often:**

100%. There are no chaotic reproduction of the bug. It is event based.

### Versions

>atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

>apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.13
git 2.10.2.windows.1
visual studio

OS: Windows 10, 1803, 17134.885

**Comment by rsese** [comment]
Thanks for the report!  This package is only for Python syntax highlighting and snippets so I don't think the issue isn't specific to this package.

> I have 4 python packages installed to my Atom IDE: autocomplete-python, ide-python, python-indent and python-tools. I disabled 4 of them and tried to reproduce the bug. Bug is reproduced.

> When I disabled, language-python package from "Core Packages" the bug didn't reproduce. So, I decided to report this bug to related core atom package.

This is partly why we ask in the `Prerequisites` section to confirm if you can reproduce in safe mode where all community package are disabled - if it's not reproducible in safe mode, then the issue is likely caused by a community package (as a side note, you can list your community package with `apm list --installed`).  Can you reproduce in safe mode?

**Comment by canturkm** [comment]
Thanks for the answer. 

Yes. I couldn't reproduce the bug in safe mode. I had believed, all packages (including core packages) would be disabled on safe mode. So, I wouldn't test this bug on safe mode. However, that assumption was not true. 

I understand now, it is not a bug related to this package. Bug is related to Nuclide package. 

There is no info icons on local python files. Just remote nuclide files has that info icons. And that bug is related to retired nuclide package. 

"Nuclide provides built-in diagnostics for Python, currently displaying lint messages from flake8."

https://nuclide.io/docs/languages/python/

**Comment by canturkm** [comment]
I solved my problem by disabling diagnostics in Nuclide. 

Packages > Settings View > Installed Packages/Themes > Packages > nuclide > Settings > Enabled Features > "Enable Diagnostics"

and set "Enable Diagnostics" to "Never Enabled"

![nuclide-error](https://user-images.githubusercontent.com/10234479/63706746-df349600-c838-11e9-9eef-4d3fb397a2a4.png)

**Comment by canturkm** [comment]
Oh. Thank you for help. I will try it.
