### ISSUE TITLE
Type annotations break function arguments coloration

### ISSUE THREAD

**Issue by Hellzed** [atom/language-python#312]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

With tree sitter enabled, adding type annotations to function arguments breaks argument coloration.
![image](https://user-images.githubusercontent.com/1180536/68548149-08050a00-03ea-11ea-8884-bde2f56358a3.png)
![image](https://user-images.githubusercontent.com/1180536/68548133-eb68d200-03e9-11ea-991e-7e475e4fcca7.png)

### Steps to Reproduce

Add type annotations to a function argument

**Expected behaviour:**

Argument coloration should remain the same with or without a type annotation.

**Actual behavior:**

Argument coloration disappears, the argument is now of default text colour.

**Reproduces how often:**

Always.

### Versions

Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.17rc1
git 2.20.1

**Comment by darangi** [comment]
@Hellzed Thanks!

This seems to be fixed by https://github.com/atom/language-python/pull/228#event-1441527974, the team will look into this.
