### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by aminya** [atom/language-python#330]
Could you release a new version and add it to the atom core? 

https://github.com/kiteco/atom-plugin/pull/704 is awaiting the fix from #325.

**Comment by aminya** [comment]
@darangi @sadick254

**Comment by ThatXliner** [comment]
Yes please! But then, I'll be waiting for the next Atom release. Although I do remember a way to get this on the current version...

**Comment by darangi** [comment]
`language-python@v0.53.6` has been published.
