### ISSUE TITLE
PEP 8 recommends spaces for indenting

### ISSUE THREAD

**Issue by ericwhyne** [atom/language-python#46]
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
Normalization and auto-indenting uses Tab with no option to change it to space.

"Python 3 disallows mixing the use of tabs and spaces for indentation.
Python 2 code indented with a mixture of tabs and spaces should be converted to using spaces exclusively."

**Comment by msabramo** [comment]
Using Version 0.165.0, I just created a new file and set the grammar to python and typed a simple Python class. It seems to have used spaces; not tabs. What's the problem you're seeing?

**Comment by v3ss0n** [comment]
Use softwarp (it will make tab , to spaces)

**Comment by 50Wliu** [comment]
This is now implemented.
