### ISSUE TITLE
Function Annotation (return type annotation) breaks syntax highlighting

### ISSUE THREAD

**Issue by natec425** [atom/language-python#51]
The attached image should be pretty descriptive of the problem. The grammar just doesn't seem to support function annotation. You can see that it doesn't syntax highlight the names/string annotating foo and bar. However, including the return type annotation breaks the syntax highlighting for following sections

![image](https://cloud.githubusercontent.com/assets/1424988/5888889/626f0bbe-a3d5-11e4-9214-32da5ddb315f.png)

**Comment by dveselov** [comment]
Any progress on this issue?

**Comment by nbren12** [comment]
I am experiencing this as well

**Comment by 50Wliu** [comment]
Closing as a duplicate of #68 since that has more discussion on it.
