### ISSUE TITLE
Broken syntax highlighting when writing multiple list indexes

### ISSUE THREAD

**Issue by Dentosal** [atom/language-python#60]
Example:

![screen shot 2015-05-12 at 20 57 54](https://cloud.githubusercontent.com/assets/2204863/7594497/acaac1f0-f8e9-11e4-992f-c3300d95bb33.png)

**Comment by matthewrees** [comment]
I can confirm this. The syntax highlighting seems to break with the inclusion of a third "[" character.

**Comment by 50Wliu** [comment]
Was fixed by #60.
