### ISSUE TITLE
Auto-generated quote and bracket jump doesn't work with escape sequence

### ISSUE THREAD

**Issue by kwiknik** [atom/language-python#74]
E.g. type `('\n`, the text created will be `('\n')` with the cursor just after `\n`.

Now if you type single quote (`'`) the cursor will insert a new single quote, not jump to the auto-generated one.

Similarly, typing the closing bracket (`(`) won't jump the cursor to that closing bracket, instead it'll insert a new one.

Please fix this, it's very annoying for common cases such as `split('\n')`.

**Comment by 50Wliu** [comment]
I believe this was fixed a while ago in bracket-matcher.
