### ISSUE TITLE
Highlight for 'in' keyword

### ISSUE THREAD

**Issue by nice-shot** [atom/language-python#75]
I've noticed that the `in` keyword doesn't have syntax highlighting:
<img width="274" alt="screen shot 2015-07-04 at 10 44 12 am" src="https://cloud.githubusercontent.com/assets/2602328/8507016/ee086ef8-2239-11e5-8d35-3a15daf9517f.png">

It should probably have the same color as the `for` keyword or something...

**Comment by pchaigno** [comment]
Looks fixed:
```python
for i in range(30):
  print i
```

**Comment by 50Wliu** [comment]
Confirmed fixed on Atom 1.0.7, thanks @pchaigno :sparkles:.
