### ISSUE TITLE
Disallow folding of try blocks

### ISSUE THREAD

**Issue by alexjurkiewicz** [atom/language-python#76]
Atom allows folding this code:

``` python
try:
    print("hi")
except:
    print("uh oh")
```

To this:

``` python
try:
except:
```

Unlike folding a function or flow control block (if, while, etc), there's no context above the fold showing what is within. Additionally you end up with two top level folds which seems logically incorrect.

Folding of try/except blocks just ends up annoying me when I 'fold all' on the current file -- I'd like it not to happen.

**Comment by nicktimko** [comment]
Slight devil's advocate: you could equate `else:` to `try:` and `if (expr):` to `except (exception_type):`, so they aren't *totally* context free.

**Comment by alexjurkiewicz** [comment]
True.

Being able to fold `try: ... except: ...` to something like `try: [except IOError]` would be neat (where Atom puts the `[except IOError]` text in when you fold).

So I guess that requires:
1. Folding `try: ... except: ...` to a single `try:` line
2. Adding context to the folded `try:` line

**Comment by nicktimko** [comment]
You can have an arbitrary amount of except blocks; would you do `try: [except IOError], [except ValueError] [except]`?

**Comment by alexjurkiewicz** [comment]
Other cases:
1. Multiple exceptions per except block
2. The grouping of exceptions is relatively unconstrained syntax (tuple, list, set, ...)

So you could end up with: `try: [except (IOError, TypeError)], [except [RuntimeError, KeyboardInterrupt]], [except set(SystemExit, MyError)] [except]`

This could get pretty messy. I guess the usual case is simple, so you could truncate after _n_ characters: `try: [except IOError, TypeError], [ex...`

**Comment by jrial** [comment]
Not sure I see the need for this. Some people may have a preference different from yours; I for example would like to be able to fold entire try/catch blocks if I'm not interested in the contents. Whether you fold it or not is up to you; if you don't want to fold it, don't click the fold icon.

It's perhaps an annoyance when you fold to a certain level, e.g. "Fold Level 3". But even then it's a small annoyance. And the solutions proposed here seem much too complex given the severity of the "issue".

What am I missing?
