### ISSUE TITLE
Mistakenly highlights DELETE in quotes as keyword

### ISSUE THREAD

**Issue by mcandre** [atom/language-python#79]
language-python mistakenly highlights `DELETE` in:

```python
class Call(object):
    _valid_methods = ['GET', 'POST', 'PUT', 'DELETE', 'HEAD']
```

as a keyword, even though it is inside quotes, indicating it is a string.

**Comment by infininight** [comment]
This is due to `DELETE` being an SQL keyword so it sees the string as an SQL string and passes the contents of the string to the SQL grammar for highlighting. Not really a way to fix this without just removing the SQL integration.

**Comment by jolsenmultiad** [comment]
Would it be acceptable to make SQL integration optional via a setting (at least until a more proper fix is found), so those of us who would rather have SQL statements look like regular quoted strings with no SQL highlighting can turn the integration off, versus experiencing this and the other highlighting problems issues #101, #110, and #118?

**Comment by mcandre** [comment]
> Would it be acceptable to make SQL integration optional via a setting

yes, that's a decent workaround

**Comment by 50Wliu** [comment]
Closing in favor of #110 in order to consolidate the issue reports - feel free to subscribe there for updates.

**Comment by mohans07** [comment]
> language-python mistakenly highlights `DELETE` in:
> 
> ```python
> class Call(object):
>     _valid_methods = ['GET', 'POST', 'PUT', 'DELETE', 'HEAD']
> ```
> 
> as a keyword, even though it is inside quotes, indicating it is a string.
how to overcome this
