### ISSUE TITLE
Really weird highlighting issues

### ISSUE THREAD

**Issue by kirbyfan64** [atom/language-python#86]
Basically, I'm going to use Linguist as an example, but the same thing occurs with Atom. I'm just too lazy to take screenshots. :)

Take a look at:

- [Syntax highlighting randomly turned off.](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L178)
- [It's kind of on again.](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L190)
- [Now it's back.](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L196)
- [Lost it again.](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L196)
- [Black docstring.](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L277)
- [Only the docstring end was detected here, so it completely screws up highlighting for the entire rest of the file.](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L545)

All of these issues are from [one file](https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py). Now, as I said, these all also occur in Atom, which makes editing Python files...fun. :/

**Comment by kirbyfan64** [comment]
Docstring issues seem to be #55?

**Comment by auscompgeek** [comment]
By the nature of the project, `mypy` use function annotations everywhere. This entire issue appears to just be #68 (even the docstring issues).

**Comment by 50Wliu** [comment]
Closing in favor of #68.
