### ISSUE TITLE
New async/await keyword

### ISSUE THREAD

**Issue by harai** [atom/language-python#93]
[`async`/`await` keyword](https://www.python.org/dev/peps/pep-0492/) will be added in upcoming Python 3.5.

It would be very happy if they are supported in this package.

**Comment by monkpit** [comment]
I've added `await` and `async def` in 2 PRs, this could be closed after they are merged.

I chose not to make `async` alone an illegal_term because if you fire up python 3.5:

```python
async = 'noodles'
async def test():
    pass
```

Works just fine. So `async` as an identifier is not off-limits.

**Comment by TheTechNick** [comment]
Hi,
the `async def` highlighting is not merged in the `master`-branch, only the `await` keyword made it.
It would be great to see the complete highlighting of [PEP 492](https://www.python.org/dev/peps/pep-0492/) in this package. (async def, async for, async with, ...)

**Comment by monkpit** [comment]
Check out discussion from https://github.com/atom/language-python/pull/108 for more details

**Comment by dimaqq** [comment]
Ping...

**Comment by PhydeauxLeChien** [comment]
Any progress on this?

**Comment by jakeschurch** [comment]
Would love to see this implemented!

**Comment by tiaod** [comment]
Two years later..
