### ISSUE TITLE
Support for Type Hints (PEP484)

### ISSUE THREAD

**Issue by andrefreitas** [atom/language-python#94]
Python 3.5 is a stable release that introduces Type Hints as described in PEP484 https://www.python.org/dev/peps/pep-0484/ 

```python
def greeting(name: str) -> str:
    return 'Hello ' + name
```
Would be good to support this in language-python package.

**Comment by 50Wliu** [comment]
Is there a difference between this and #68?

**Comment by andrefreitas** [comment]
@50Wliu Type Hints syntax uses the convention used in that issue, that refers to PEP3107 Function Annotations. So yes, there is basically no difference.

**Comment by 50Wliu** [comment]
Ok, in that case, I'm going to close this in favor of #68 to keep discussion unified.
