### ISSUE TITLE
Paint functions with color!

### ISSUE THREAD

**Issue by wafflespeanut** [atom/language-python#97]
For Rust, Atom highlights the functions with color, something like this...

![rust](https://cloud.githubusercontent.com/assets/6691262/9979933/aae67ad8-5fa2-11e5-939c-b50922ec397d.png)

But, it doesn't do it for Python...

![python](https://cloud.githubusercontent.com/assets/6691262/9979942/c9b9a336-5fa2-11e5-9b6e-7ff4e4b318d7.png)

<small> **Atom version:** 1.0.11 </small>

**Comment by 50Wliu** [comment]
Closing in favor of #170.
