### ISSUE TITLE
Highlight self and cls in method argument list

### ISSUE THREAD

**Issue by rumpelsepp** [atom/language-python#99]
IMO it makes sense, when `self` and `cls` in method argument lists are highlighted as well. Sublime Text does this IIRC and it makes class code more readable, since these common used keywords are better seperated from the important arguments.

![screenshot from 2015-09-22 16-06-00](https://cloud.githubusercontent.com/assets/1961699/10020625/305478da-6144-11e5-8c50-84b1e8857978.png)

**Comment by 50Wliu** [comment]
All parameters in function definitions are now tokenized.  Please tell me if this isn't what you're looking for.
